In [4]:
import numpy as np

## Replace list of index x,y of np array with specific value
- numpy array can handle list of indices
- array elements can be modified with lambda functions in the index

In [2]:
ar_1 = np.array([[-1,0,1], [-2,0,2], [-1,0,1]])
ar_1

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [4]:
ar1_x_ind = [0,1,2]
ar1_y_ind = [0,1,2]

In [5]:
# replace with index list value with 1
ar_1[ar1_x_ind,ar1_y_ind] = 1
ar_1

array([[ 1,  0,  1],
       [-2,  1,  2],
       [-1,  0,  1]])

In [7]:
ar_1[ar_1 != 1] = 0
ar_1

array([[1, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

 ## Others

In [6]:
scores = np.array([(90,70,100),(100,90,45),(80,60,70)])
mean_scores = np.mean(scores,axis=0)
mean_scores

array([90.        , 73.33333333, 71.66666667])

In [7]:
normalised_scores = scores - mean_scores
normalised_scores

array([[  0.        ,  -3.33333333,  28.33333333],
       [ 10.        ,  16.66666667, -26.66666667],
       [-10.        , -13.33333333,  -1.66666667]])

In [16]:
corr_scores = np.cov(normalised_scores.T)
Eigen_value, Eigen_vector = np.linalg.eig(corr_scores)
print ("Eigen_value : ", Eigen_value)
print ("Eigen_vector : ", Eigen_vector)

Eigen_value :  [9.01760331e+02 1.50389412e-14 1.89906336e+02]
Eigen_vector :  [[-0.2130403  -0.80221712  0.55772889]
 [-0.39344552  0.59294309  0.70258033]
 [ 0.89432346  0.06975801  0.4419495 ]]


In [18]:
projeced_matrix = Eigen_vector.T.dot(normalised_scores.T)
projeced_matrix.T

array([[ 2.66506498e+01, -3.25364539e+01,  5.88580411e+00],
       [-1.16773352e-15,  9.27812443e-16,  7.82507298e-15],
       [ 1.01799682e+01,  5.50164096e+00, -1.56816091e+01]])

In [19]:
Eigen_vector.T.dot(normalised_scores)

array([[-12.8776898 , -17.7716038 ,   2.96519956],
       [  5.2318508 ,  11.62633511, -38.65756423],
       [  2.60630823,   3.95791575,  -3.66973923]])

In [16]:
x = np.array([(1),(1),(1),(1)])
x

array([1, 1, 1, 1])

In [33]:
x_arr = x.reshape(4,1)
x_arr

array([[1],
       [1],
       [1],
       [1]])

In [31]:
y = np.array([1,2,3,4,5,6,7,8])
y_arr = y.reshape(4,1,2)
y_arr

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]],

       [[7, 8]]])

In [36]:
y_arr[x_arr == 1]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
x_arr == 1

array([[ True],
       [ True],
       [ True],
       [ True]])

In [38]:
b = np.array([[[1, 2, 3],[4, 5, 6]],
            [[7, 8, 9],[10, 11, 12]]])
b.shape

(2, 2, 3)

In [46]:
a1 = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = a1.sum(-1)
sumrow

array([10,  9, 20])

In [63]:
x = np.array([1,2]).reshape(1,2)
a,b = x.ravel()
x

array([[1, 2]])

In [62]:
x.ravel()

array([1, 2])

In [54]:
a

1